Apply Smarty Security Policy and replace usage of `{crmAPI}` in affected templates
systopia/de.systopia.remoteevent pull request #104
Opened 2024-12-05 13:22 UTC by jensschuppe

The extension's utility method for rendering *Smarty* templates does not apply the Smarty User Content Policy introduced with CiviCRM `5.74.4` and `5.69.6`. Although rendering currently does not explicitly involve user content, it's safer to apply the policy and make default templates compatible by replacing usages of the `{crmAPI}` *Smarty* tag which is considered insecure by CiviCRM Core and thus causes an error with the policy applied.

There has been only one occurrence of the `{crmAPI}` *Smarty* tag in the extension's templates, which can be easily replaced by adding a template variable instead.

As which template is rendered is subject to Symfony event listener implementations, this PR should be included in a major (BC-breaking) or a minor version only with explicit documentation.

2024-12-06 08:51 UTC, bjendres approved these changes
This should be fine, since people who want a customised presenter name (not just ``display_name``), could still use the ``RenderEvent`` triggered right after this.

2024-12-06 15:33 UTC, dontub requested changes

2024-12-06 15:33 UTC, dontub commented on Civi/RenderEvent.php
> +    protected $original_template_file;
Can we use a PHP type hint?

2024-12-06 15:33 UTC, dontub commented on Civi/RenderEvent.php
> +        $rendered_text = \CRM_Utils_String::parseOneOffStringThroughSmarty($template, $render_event->getVars());
This leads to an error in `CRM_Remoteevent_SessionTest::testSessionPrefill()` https://github.com/systopia/de.systopia.remoteevent/actions/runs/12196568086/job/34024413779?pr=104#step:6:28

2025-02-20 16:57 UTC, bjendres approved these changes
Looks very sensible to me, but haven't tested.

2025-02-20 16:57 UTC, merged